export const primaryColor = "#ff6a00";
export const Color1 = "#fa6d01";
export const Color2 = "#34ccc1";
export const Color3 = "green";
export const edgeColor = "steelblue";

export const data = {
  nodes: [
    {
      id: "node-0",
      label: "QN1",
      size: 100,
      x: 100,
      y: 150,
      type: "quantum-node",
      color: Color1,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "pi/2, 0",
      phi: (0 * Math.PI) / 24,
      theta: (5 * Math.PI) / 10
    },
    {
      id: "node-1",
      label: "QN2",
      size: 100,
      x: 100,
      y: 300,
      type: "quantum-node",
      color: Color1,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "pi/2, pi/4",
      phi: (6 * Math.PI) / 24,
      theta: (5 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-2",
      label: "QN3",
      size: 100,
      x: 100,
      y: 450,
      type: "quantum-node",
      color: Color1,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "pi/2, pi/2",
      phi: (12 * Math.PI) / 24,
      theta: (5 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-3",
      label: "QN4",
      size: 100,
      x: 100,
      y: 600,
      type: "quantum-node",
      color: Color1,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "pi/2, pi3/4",
      phi: (18 * Math.PI) / 24,
      theta: (5 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-4",
      label: "QN5",
      size: 100,
      x: 100,
      y: 750,
      type: "quantum-node",
      color: Color1,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "pi/2, pi",
      phi: (24 * Math.PI) / 24,
      theta: (5 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-5",
      label: "QN6",
      size: 100,
      x: 100,
      y: 900,
      type: "quantum-node",
      color: Color1,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "pi/2, 5/4pi",
      phi: (30 * Math.PI) / 24,
      theta: (5 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-6",
      label: "QN7",
      size: 100,
      x: 100,
      y: 1050,
      type: "quantum-node",
      color: Color1,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "pi/2, 3/2pi",
      phi: (36 * Math.PI) / 24,
      theta: (5 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-7",
      label: "QN8",
      size: 100,
      x: 300,
      y: 150,
      type: "quantum-node",
      color: Color2,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "0, pi/2",
      phi: (12 * Math.PI) / 24,
      theta: (0 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-8",
      label: "QN9",
      size: 100,
      x: 300,
      y: 300,
      type: "quantum-node",
      color: Color2,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "1/10pi, pi/2",
      phi: (12 * Math.PI) / 24,
      theta: (1 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-9",
      label: "QN10",
      size: 100,
      x: 300,
      y: 450,
      type: "quantum-node",
      color: Color2,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "2/10pi, pi/2",
      phi: (12 * Math.PI) / 24,
      theta: (2 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-10",
      label: "QN11",
      size: 100,
      x: 300,
      y: 600,
      type: "quantum-node",
      color: Color2,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "3/10pi, pi/2",
      phi: (12 * Math.PI) / 24,
      theta: (3 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-11",
      label: "QN12",
      size: 100,
      x: 300,
      y: 750,
      type: "quantum-node",
      color: Color2,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "4/10pi, pi/2",
      phi: (12 * Math.PI) / 24,
      theta: (4 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-12",
      label: "QN13",
      size: 100,
      x: 300,
      y: 900,
      type: "quantum-node",
      color: Color2,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "pi/2, pi/2",
      phi: (12 * Math.PI) / 24,
      theta: (5 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-13",
      label: "QN14",
      size: 100,
      x: 500,
      y: 150,
      type: "quantum-node",
      color: Color2,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "6/10pi, pi/2",
      phi: (12 * Math.PI) / 24,
      theta: (6 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-14",
      label: "QN15",
      size: 100,
      x: 500,
      y: 300,
      type: "quantum-node",
      color: Color2,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "7/10pi, pi/2",
      phi: (12 * Math.PI) / 24,
      theta: (7 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-15",
      label: "QN16",
      size: 100,
      x: 500,
      y: 450,
      type: "quantum-node",
      color: Color2,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "8/10pi, pi/2",
      phi: (12 * Math.PI) / 24,
      theta: (8 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-16",
      label: "QN17",
      size: 100,
      x: 500,
      y: 600,
      type: "quantum-node",
      color: Color2,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "9/10pi, pi/2",
      phi: (12 * Math.PI) / 24,
      theta: (9 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-17",
      label: "QN18",
      size: 100,
      x: 500,
      y: 750,
      type: "quantum-node",
      color: Color2,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "pi, pi/2",
      phi: (12 * Math.PI) / 24,
      theta: (10 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-18",
      label: "QN19",
      size: 100,
      x: 700,
      y: 150,
      type: "quantum-node",
      color: Color3,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "0, pi/4",
      phi: (6 * Math.PI) / 24,
      theta: (0 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-19",
      label: "QN20",
      size: 100,
      x: 700,
      y: 300,
      type: "quantum-node",
      color: Color3,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "1/10pi, pi/4",
      phi: (6 * Math.PI) / 24,
      theta: (1 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-20",
      label: "QN21",
      size: 100,
      x: 700,
      y: 450,
      type: "quantum-node",
      color: Color3,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "2/10pi, pi/4",
      phi: (6 * Math.PI) / 24,
      theta: (2 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-22",
      label: "QN23",
      size: 100,
      x: 700,
      y: 600,
      type: "quantum-node",
      color: Color3,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "3/10pi, pi/4",
      phi: (6 * Math.PI) / 24,
      theta: (3 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-23",
      label: "QN24",
      size: 100,
      x: 700,
      y: 750,
      type: "quantum-node",
      color: Color3,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "4/10pi, pi/4",
      phi: (6 * Math.PI) / 24,
      theta: (4 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-24",
      label: "QN25",
      size: 100,
      x: 700,
      y: 900,
      type: "quantum-node",
      color: Color3,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "pi/2, pi/4",
      phi: (6 * Math.PI) / 24,
      theta: (5 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-25",
      label: "QN26",
      size: 100,
      x: 900,
      y: 150,
      type: "quantum-node",
      color: Color3,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "6/10pi, pi/4",
      phi: (6 * Math.PI) / 24,
      theta: (6 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-26",
      label: "QN27",
      size: 100,
      x: 900,
      y: 300,
      type: "quantum-node",
      color: Color3,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "7/10pi, pi/4",
      phi: (6 * Math.PI) / 24,
      theta: (7 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-27",
      label: "QN28",
      size: 100,
      x: 900,
      y: 450,
      type: "quantum-node",
      color: Color3,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "8/10pi, pi/4",
      phi: (6 * Math.PI) / 24,
      theta: (8 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-28",
      label: "QN29",
      size: 100,
      x: 900,
      y: 600,
      type: "quantum-node",
      color: Color3,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "9/10pi, pi/4",
      phi: (6 * Math.PI) / 24,
      theta: (9 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    },
    {
      id: "node-29",
      label: "QN30",
      size: 100,
      x: 900,
      y: 750,
      type: "quantum-node",
      color: Color3,
      projection: [60, -20],
      pseudoProjection: true,
      hideAxis: false,
      hidePoles: false,
      vector: "pi, pi/4",
      phi: (6 * Math.PI) / 24,
      theta: (10 * Math.PI) / 10,
      state: [0.1, 0.7, 0.3]
    }
  ],
  edges: [],
  paths: [{ edges: ["edge1"], nodes: ["node-1", "node-2"] }],
  hulls: []
};
